### ISSUE TITLE
メールアドレスでのログインに失敗する

### ISSUE THREAD

**Issue by yunosuke924** [among-use/among-use#38]
- メールアドレスでのログインに失敗します。
- Githubログインはできます。
- Githubログインしたユーザーはメールアドレスでログインすることはないと思うので、ログイン画面にGithubログインのボタンを設けたい
![3ae32357da40158f914565d436dc8487](https://user-images.githubusercontent.com/72934392/128458446-5990d305-52ad-453d-a277-c4184ff890fc.gif)

**Comment by SakitaDaiki0623** [comment]
ここは自分がやりまーす！
