### ISSUE TITLE
Githubログイン後に開発環境から本番環境に遷移してしまう

### ISSUE THREAD

**Issue by yunosuke924** [among-use/among-use#60]
開発環境でGithubログイン後に本番環境に遷移してしまう。
![e2ccd5cff4fbde68acde530e88477872](https://user-images.githubusercontent.com/72934392/129460674-88c222e4-455e-40c3-b59b-2e3b0ea3ed52.gif)

**Comment by SakitaDaiki0623** [comment]
@yunosuke924 
これは正常に動作していますね！
GitHubアプリ上でリダイレクトURLを本番環境用URLに移しているためです！
前までは開発環境用のlocalhost:3000でした。

**Comment by yunosuke924** [comment]
なるほど、ということは開発環境でのGithubログインを用いた検証は不可で、メールアドレスでログインしておく必要があるという認識で良いでしょうか？

**Comment by SakitaDaiki0623** [comment]
「Authorization callback URL」で認証後のリダイレクト先URLを設定できるのですが、GitHubは一つしか設定できないようですね、、、(Slackは複数設定できます)

[![Image from Gyazo](https://i.gyazo.com/9cd12909ea820cbc38b8ff72376001b2.png)](https://gyazo.com/9cd12909ea820cbc38b8ff72376001b2)

ですので、基本的にはメールアドレスログインしか開発環境ではログインできないと思います。
もし開発環境でのGithubログインを用いた検証を行うのであれば、本番環境をメンテナンスモードにしてその後コールバックURLを開発環境にするという手順になると思います。
