### ISSUE TITLE
本番環境でCREWSが確認できない

### ISSUE THREAD

**Issue by yunosuke924** [among-use/among-use#61]
本番環境にてユーザー一覧を確認するとエラーが出ます。
- 現状、saitoさん以外が本番環境にてログの確認ができないので、一時的にデバッグ画面表示させても良い？

![449deee1a73a45e39d136d3ab8a56c20](https://user-images.githubusercontent.com/72934392/129460756-69d30886-b25f-47a9-9a40-2d7cf38f8b23.gif)

**Comment by SakitaDaiki0623** [comment]
最新のmasterをpullしたら下記のようなエラーになってます。

[![Image from Gyazo](https://i.gyazo.com/7bdae0c3b56ea32e10985dd3714257e8.png)](https://gyazo.com/7bdae0c3b56ea32e10985dd3714257e8)

多分これで修正可能

```ruby
      <% if user.profile.present? %>
      <div class="text-overflow">
        <%= user.profile.message.truncate(20) %>
      </div>
    <% end %>
```
